roads_of_armenia/apps/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

roads_of_armenia/roads_of_armenia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app', include('apps.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

roads_of_armenia/users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    path('', views.home, name='reg_home'),
    path('signup/<int:key>', views.UserSignUpView.as_view(), name='up'),
    path('client_page', views.client_page, name='client_page'),
    path('tour_creation', views.tour_creation, name='tour_creation'),
    path('driver_list', views.driver_list, name='driver_list'),
    path('guide_list', views.guide_list, name='guide_list'),
    path('agent_list', views.agent_list, name='agent_list'),
    path('tour_list', views.tour_list, name='tour_list'),

    path('pic_upload/<int:user_id>/', views.pic_upload, name='pic_upload'),
    path('in/', views.login_0, name='login'),
    path('out/',views.u_logout, name='logout'),

    
]

roads_of_armenia/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
import datetime
from .choices import *
from multiselectfield import MultiSelectField


def year_choices():
    return [(r, r) for r in range(1984, datetime.date.today().year+1)]


class User(AbstractUser):
    username = models.CharField(blank=True, max_length=255)
    email = models.EmailField(_('email address'), unique=True)
    # bank_account = models.CharField(max_length=255)
    # name = models.CharField(max_length=255)
    # phone_number = models.CharField(max_length=30)
    user_choices = models.IntegerField(choices=USER_CHOICES, default=1)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    def __str__(self):
        return "{}".format(self.email)


class Client(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE, related_name='client')
    bonus = models.IntegerField()
    history = models.CharField(max_length=255)


class Driver(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE, related_name='driver')
    name = models.CharField(max_length=255)
    language = MultiSelectField(_('language'), choices=LANGUAGES_CHOICES)
    about_me = models.CharField(max_length=255)
    profile_image = models.ImageField(upload_to='img', null=True)
    gender = models.IntegerField(choices=GENDER_CHOICES)
    age = models.IntegerField(choices=AGE_CHOICES)
    experience = models.IntegerField()
    free_days = MultiSelectField(choices=WEEK_DAY_CHOICES)

    car = models.IntegerField(choices=CAR_CHOICES,)
    production_year = models.IntegerField(_('year'), choices=year_choices())
    seats = models.IntegerField()
    kid_seats = models.BooleanField(default=False)
    invalid_chairs = models.BooleanField(default=False)
    price_per_km = models.IntegerField()


class CarImageModel(models.Model):
    mainimage = models.ImageField(upload_to='img', null=True)
    image = models.ForeignKey(Driver, on_delete=models.CASCADE, related_name='aa')

# class Car(models.Model):
#     car = models.IntegerField(choices=CAR_CHOICES,)
#     production_year = models.IntegerField(_('year'), choices=year_choices())
#     seats = models.IntegerField()
#     kid_seats = models.BooleanField(default=False)
#     invalid_chairs = models.BooleanField(default=False)
#     image = models.ImageField(upload_to='img', null=True)

class Guide(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE, related_name='guide')
    name = models.CharField(max_length=255)
    language = MultiSelectField(choices=LANGUAGES_CHOICES)
    about_me = models.CharField(max_length=255)
    profile_image = models.ImageField(upload_to='img', null=True)
    gender = models.IntegerField(choices=GENDER_CHOICES)
    age = models.IntegerField(choices=AGE_CHOICES)
    experience = models.IntegerField()
    tour_type = models.IntegerField(choices=TOUR_CHOICES)
    region = models.IntegerField(choices=REGION_CHOICES)
    free_days = MultiSelectField(choices=WEEK_DAY_CHOICES)
    trip_image = models.ImageField(upload_to='img', null=True, blank=True)
    car_availability = models.BooleanField(default=False)

    car = models.IntegerField(choices=CAR_CHOICES,null=True)
    production_year = models.IntegerField(_('year'), choices=year_choices(), null=True)
    seats = models.IntegerField(null=True)
    kid_seats = models.BooleanField(default=False, null=True)
    invalid_chairs = models.BooleanField(default=False, null=True)
    car_image = models.ImageField(upload_to='img', null=True, blank=True)


    def __str__(self):
        return self.name




class GuideImageModel(models.Model):
    mainimage = models.ImageField(upload_to='img', null=True)
    image = models.ForeignKey(Guide, on_delete=models.CASCADE)




class TourAgents(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE, related_name='touragents') 
    name = models.CharField(max_length=255)   
    # language = models.IntegerField(_('language'), choices=LANGUAGES_CHOICES)
    about_me = models.CharField(max_length=255)
    tour_type = models.IntegerField(_('tour_type'), choices=TOUR_CHOICES)
    # location = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Tour(models.Model):
    tour = models.ForeignKey(TourAgents, on_delete=models.CASCADE)
    rout = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField(default=0)
    date_of_tour = models.DateField(_("Date"), default=datetime.date.today)
    amount_of_place_left = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name

class TourImage(models.Model):
    mainimage = models.ImageField(upload_to='img', null=True, blank=True)
    image = models.ForeignKey(Tour, on_delete=models.CASCADE)

    def __str__(self):
        return self.image.name 

class TourAgentImage(models.Model):
    mainimage = models.ImageField(upload_to='img', null=True, blank=True)
    image = models.ForeignKey(TourAgents, on_delete=models.CASCADE)

    def __str__(self):
        return self.image.name 

roads_of_armenia/users/views.py
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import CreateView
from django.urls import reverse

from .forms import * 
from .models import User, Driver, CarImageModel, Guide, TourAgents, Tour, TourImage

from .filters import DriverFilter, TourAgentsFilter, GuideFilter, TourFilter
import datetime


def func_valid_input(key):
    try:
        name = request.GET[key]
    except:
        name = False
    return name



def home(request):
    return render(request, 'users/reg_home.html')


class UserSignUpView(CreateView):
    model = User
    form_class = CustomUserForm
    template_name = 'users/signup.html'

    def get_context_data(self, **kwargs):
        filter_key = self.kwargs['key']
        filter_dict = {'1':CollectionTitleFormSet, '2': CollectionTitleFormSetClient,
                        '3': CollectionTitleFormSetGuide, '4': CollectionTitleFormSetTourAgents
                    }
        user_coll_type = filter_dict[str(filter_key)]
        ###__________function for formset choice________###
        def filter_type(TitleFormSet,key):  
            data = super(UserSignUpView, self).get_context_data(**kwargs)
            if self.request.POST:
                print(self.request.FILES)
                data['titles'] = TitleFormSet(self.request.POST,self.request.FILES)
                
            else:
                data['titles'] = TitleFormSet()
                data['form'].fields['user_choices'].initial = key
            return data    

        data = filter_type(user_coll_type,filter_key)
        
        return data

    def form_valid(self, form):
        
        context = self.get_context_data()
        titles = context["titles"]
        # print(titles.__dict__)

        self.object = form.save()
        user_choices = form.cleaned_data.get('user_choices')

        if titles.is_valid(): 
            titles.instance = self.object
            titles.save()
            valid = super().form_valid(form)
            self.username = form.cleaned_data['email']
            self.password = form.cleaned_data['password1']
            self.user_choices = form.cleaned_data.get('user_choices')
            ####_______here must be checked if such kind of user exists_____#######
            self.user = authenticate(email=self.username,password=self.password)
        
            if self.user is not None:
                login(self.request,self.user)

        return valid
    # @login_required    
    def get_success_url(self,**kwargs):
        url_dict = {'1': '/driver_list', '2': '/client_page',
                            '3': '/guide_list', '4': '/tour_creation'
                            }
        url = url_dict[str(self.kwargs['key'])]
        # print(self.user.is_authenticated)
        return url

def client_page(request):
    return render(request, 'users/client_page.html')

def tour_creation(request):
    if request.user.is_authenticated:
        agent = TourAgents.objects.get(user__id=request.user.id) 
        tour = Tour.objects.all().filter(tour__id=agent.id)
        context = {'tour':tour}
    # else:
    #     tour = Tour.objects.all()
    #     context = {'tour':tour}
    return render(request, 'users/tour_agent.html', context)

# @login_required
def driver_list(request):

    def func_valid_input(key):
        try:
            name = request.POST[key]
        except:
            name = False
        return name
    drivers = Driver.objects.all().prefetch_related("aa")

    driver_filter = DriverFilter(request.POST, queryset=drivers)
    

    name = func_valid_input('DriverSearch')

    if name:
        drivers = drivers.filter(name__contains=F"{name}")
    # else:
    #     drivers = driver_filter.qs

    # if not drivers.exists():
        
            
    #     drivers = Driver.objects.all().prefetch_related("aa")

    context = {'drivers':drivers, 'driver_filter': driver_filter}


    return render(request, 'users/driver_list.html', context)

    # else:
    #     return redirect("in/")    
    
    


def guide_list(request):

    def func_valid_input(key):
        try:
            name = request.POST[key]
        except:
            name = False
        return name

    guides = Guide.objects.all()


    guide_filter = GuideFilter(request.POST, queryset=guides)
    
    guides = guide_filter.qs

    if request.method == 'POST':
        form = GuideForm(request.POST)
        if form.is_valid():
            language = form.cleaned_data['language']
            name = form.cleaned_data['name']
    else:
        form = GuideForm() 

    try:
        type(language)
    except:
        language = False
    try:
        type(name)
    except:
        name = False


    if name:
        guides = guides.filter(name__contains=F"{name}") #պետք ա անունը փոխել գիդինը
    if language:
        guides = guides.filter(language__contains=language)
        

    # if not guides.exists():
    #     guides = Guide.objects.all()
    

    context = {'guides':guides, 'guide_filter':guide_filter, 'form':form}


    return render(request, 'users/guide_list.html', context)  

def agent_list(request):
    agents = TourAgents.objects.all()


    agent_filter = TourAgentsFilter(request.GET, queryset=agents)
    

    name = func_valid_input('AgentSearch')

    agents = agent_filter.qs


    context = {'agents':agents, 'agent_filter': agent_filter} 

    return render(request, 'users/agents_list.html', context)  



def tour_list(request):

    tours = Tour.objects.all()


    tour_filter = TourFilter(request.GET, queryset=tours)
    

    def func_valid_input(key):
        try:
            name = request.GET[key]
        except:
            name = False
        return name

    name = func_valid_input('AgentSearch')
    price_start = func_valid_input('PriceStart')    
    price_to = func_valid_input('PriceTo')    
    date_start = func_valid_input('DateStart')   
    date_end = func_valid_input('DateEnd')   
    quantity = func_valid_input('Quantity')

    tours = tour_filter.qs

    #########_______________ FIlter Name________________ #############
    if name:
        tours = tour_filter.qs.filter(user__name__contains=F"{name}",)


    #########_______________ FIlter Date range________________ #############

    if date_start and date_end:
        tours = tour_filter.qs.filter(date_of_tour__range=(date_start,date_end),)

    elif date_start and not date_end:
        date_end = "2100-01-01"
        tours = tour_filter.qs.filter(date_of_tour__range=(date_start,date_end),) 
    elif not date_start and date_end:
        date_start = str(datetime.date.today())
        print(date_start)
        tours = tour_filter.qs.filter(date_of_tour__range=(date_start,date_end),)


    #########_______________ FIlter price range________________ #############

    if price_start and price_to:
        tours = tours.filter(first_to_ten_price__range=(price_start,price_to),)

    elif price_start and not price_to:
        price_to = 10000000000
        tours = tours.filter(first_to_ten_price__range=(price_start,price_to),) 
    elif not price_start and price_to:
        price_start = 0
        tours = tours.filter(first_to_ten_price__range=(price_start,price_to),)

    #########_______________ FIlter quantity ________________ #############
    if quantity:
        quantity = int(quantity)
        tours = tour_filter.qs.filter(quantity=quantity,)
        


    context = {'tours':tours, 'tour_filter': tour_filter} 

    return render(request, 'users/tour_list.html', context)  


@login_required
def pic_upload(request,user_id=1):
    if request.method == "POST":

        form = TourCreationForm(request.POST)
        if form.is_valid():
            form.save()
            tour_agent = TourAgents.objects.get(user_id=user_id)
            tour_obj = Tour.objects.all().filter(tour_id=tour_agent.id)
            image = tour_obj.last()
            
            for afile in request.FILES.getlist('files'):
                tourimage = TourImage.objects.create(image=image,mainimage=afile)
            return redirect('tour_creation') 
    else:
        form = TourCreationForm()
        form.initial['tour'] = TourAgents.objects.get(user_id=user_id)
        
    return render(request, 'users/tour_creation.html', {"form": form})

def login_0(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            
            template_dict = {'1': '/driver_list', '2': '/client_page',
                            '3': '/guide_list', '4': '/tour_creation'
                            }
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,password=password)

            if user is not None:
                
                login(request,user)
                template_0 = template_dict[str(user.user_choices)]
                return redirect(template_0)
            else:
                print(request.POST)
                return HttpResponse("wrong login")
    else:
        
        form = LoginForm()

    return render(request,'users/login.html', {'form':form} )


def u_logout(request):
    logout(request)
    return redirect('/client_page')


roads_of_armenia/users/templates/users/agents_list.html
{% load static %}
<h1>Tour Agents</h1>

<div>
    {% if request.user.is_authenticated %}
      <a class="log">{{ user.email }}</a>
      <a class="log" href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a class="log" href="{% url 'login' %}">Login</a>
      <a class="reg" href="{% url 'reg_home'  %}">Register</a>
    {% endif %}
  </div>
  <br>
  <br>
  <br>


<div>
    <form method="GET">
      <li>
      <input type="text" name="AgentSearch" placeholder="type something...">
      </li>
      {{ agent_filter.form }}
      	
      <button type="submit" name="search">Search</button>
      
    </form>
</div>


{% for i in agents %}
<h2>Tour Agent</h2>
<li>
	bank account: {{i.user.bank_account}}
</li>

<li>
	Name: {{i.user.name}}
</li>

<li>
	Phone number:{{i.user.phone_number}}
</li>

<li>
	Language: {{i.get_language_display }}
</li>
<li>
	About agent: {{i.about_me}}
</li>
<li>
	Tour type: {{ i.get_tour_type_display }}
</li>

<li>
	Price :{{i.first_to_ten_price}}
</li>

<li>
	Date of tour : {{i.date_of_tour }}
</li>
<li>
      Quantity : {{i.quantity }}
</li>

<br>
<br>
<br>

{% endfor %}

roads_of_armenia/users/templates/users/client_page.html
{% load static %}
<h1>Client page<h1>
{% if request.user.is_authenticated %}
	<a class="reg" href="{% url 'logout' %}">Logout</a>
{% endif %}

<div class = "driver_list">
<a  type="button" href="{% url 'driver_list' %}">Driver</a>
</div>
<div class = "guide_list">
<a  type="button" href="{% url 'guide_list' %}">Guides</a>
</div>
<div class = "tour_agent_list">
<a  type="button" href="{% url 'agent_list' %}">Tour_agents</a>
</div>
<div class = "tour_list">
<a  type="button" href="{% url 'tour_list' %}">Tour_List</a>
</div>

roads_of_armenia/users/templates/users/driver_list.html
{% load static %}
<h1>driver list</h1>

<div>
    {% if request.user.is_authenticated %}
      <a class="log">{{ user.email }}</a>
      <a class="log" href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a class="log" href="{% url 'login' %}">Login</a>
      <a class="reg" href="{% url 'reg_home' %}">Register</a>
    {% endif %}
  </div>
  <br>
  <br>
  <br>

<div>
    <form method="POST">
      {% csrf_token %}
      <label>Driver Name</label>
      <input type="text" name="DriverSearch" placeholder="Driver Name">

      {{ driver_filter.form }}
      	
      <button type="submit" name="search">Search</button>
      
    </form>
  </div>


{% for i in drivers %}
<h3>Driver</h3>

<img src="{{i.profile_image.url}}" alt="jhsajd">


<li>
	Name: {{i.name}}
</li>

<li>
  Gender: {{i.get_gender_display}}
</li>
<br>
<li>
	Car model: {{ i.get_car_display }}
</li>
<li>
	Production Year:{{ i.get_production_year_display }}
</li>

<li>
	Car Seats: {{ i.seats }}
</li>

<li>
	Price per KM: {{ i.price_per_km }}
</li>
<br>
<br>
{% endfor %}

roads_of_armenia/users/templates/users/guide_list.html
{% load static %}
<h1>GuideList</h1>

<div>
    {% if request.user.is_authenticated %}
      <a class="log">{{ user.email }}</a>
      <a class="log" href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a class="log" href="{% url 'login' %}">Login</a>
      <a class="reg" href="{% url 'reg_home' %}">Register</a>
    {% endif %}
  </div>
  <br>
  <br>
  <br>



<div>
    <form method="POST">
      {% csrf_token %}
      
      <!-- <input type="text" name="GuideName" placeholder="type GuideName..."> -->
      {{form.language}}
      {{form.name}}
      {{ guide_filter.form }}
      
      <button type="submit" name="search">Search</button>
      
    </form>
</div>


{% for i in guides %}
<h2>Guide</h2>

<img src="{{i.profile_image.url}}" alt="jhsajd">


<li>
	Name: {{i.name}}
</li>

<br>
<li>
	Language:{{i.get_language_display}}
</li>
<li>
	About Guide:{{i.about_me}}
</li>

<li>
	Location:{{i.location}}
</li>

<br>
<br>
<br>

{% endfor %}

roads_of_armenia/users/templates/users/login.html
  <div class="login_container">
    <form action="" method="post">
      {% csrf_token %}

      <div class="form_container">
        <p class="form_title">Login Form</p>
        
        <label for="uname"><b>Email</b></label>

        {{ form.username }}

        <label for="psw" type = 'password'><b>Password</b></label>

        {{ form.password }}     
        <label for="chs" ><b>User Choices</b></label>
        {{ form.user_choices }}   
        
        
        
        <button name="submit" value="username,password" type="submit" >Login as</button>
        
        
      </div>
    </form>
  </div>

roads_of_armenia/users/templates/users/reg_home.html
{%load static%}
<h1>Hello world!!</h1>

<h2> 
	<a  type="button" href="{% url 'login' %}">Login</a>
</h2>


{% with a=1 b=2 c=3 d=4  %}
<h2>
<a  type="button" href="{% url 'up' a %}">Sign up as Driver</a>
<br>
<a  type="button" href="{% url 'up' b %}">Sign up as Client</a>
<br>
<a  type="button" href="{% url 'up' c %}">Sign up as Guid</a>
<br>
<a  type="button" href="{% url 'up' d %}">Sign up as TourAgent</a>
</h2>
{% endwith %}	

roads_of_armenia/users/templates/users/signup.html
{% load static %}
<form method="post" action='' enctype="multipart/form-data">
	{% csrf_token %}
    {{ form.as_p }}
    {{ titles.as_p }}
    
{% if request.path == "/signup/4" %}

    <table>
    	<h1> a 
    	{{ request.path }}</h1>
      <tr>
        <td>Select Pictures: </td><td><input name="files" type="file" size="50" accept="image/*" multiple required>  </td>
        <td></td>
       </tr>
    </table>
  {% endif %}
  {% if request.path == "/signup/3" %}

    	<h1> a 
    	{{ request.path }}</h1>
      <
  {% endif %}
  {% if request.path == "/signup/2" %}

    	<h1> a 2
    	{{ request.path }}</h1>
      <
  {% endif %}
    <input type="submit" value="Save">
</form>

roads_of_armenia/users/templates/users/tour_agent.html
{% load static %}
<h1> Tour agent home view</h1>

{% for i in tour %}
<li>
	{{ i.name}}
</li>	
{% endfor %}
{% if user.is_authenticated %}
	<a href="{% url 'pic_upload' request.user.id %}" type="buttom"> new</a>
{% endif %}

roads_of_armenia/users/templates/users/tour_agent_page.html
<h1> Tour agents page </h1>
<form action="/pic_upload/{{request.user.id}}/" method="post" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.as_p }} 
    <table>
      <tr>
        <td>Select Pictures: </td><td><input name="files" type="file" size="50" accept="image/*" multiple>  </td>
        <td><button type="submit"> Upload </button> </td>
       </tr>
    </table>
</form>

roads_of_armenia/users/templates/users/tour_creation.html
<h1> Tour creation page </h1>
<form action="/pic_upload/{{request.user.id}}/" method="post" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.as_p }} 
    <table>
      <tr>
        <td>Select Pictures: </td><td><input name="files" type="file" size="50" accept="image/*" multiple>  </td>
        <td><button type="submit"> Upload </button> </td>
       </tr>
    </table>
</form>

roads_of_armenia/users/templates/users/tour_list.html
<h1>Tours</h1>


<div>
    <form method="GET">
      <li>
      <input type="text" name="AgentSearch" placeholder="type Agent name...">
      </li>
      <li>
      <input type="date" name="DateStart" placeholder="Start Date ...">
      </li>
      <li>
      <input type="date" name="DateEnd" placeholder="End Date...">
      </li>
      <li>
      <input type="number" name="PriceStart" placeholder="PriceStart...">
      </li>
      <li>
      <input type="number" name="PriceTo" placeholder="PriceTo...">
      </li>
      <li>
      <input type="number" name="Quantity" placeholder="Quantity...">
      </li>
      {{ tour_filter.form }}
      	
      <button type="submit" name="search">Search</button>
      
    </form>
</div>


{% for i in tours %}
<h2>Tour Agent</h2>
<li>
	bank account: {{i.user.bank_account}}
</li>

<li>
	Name: {{i.user.name}}
</li>

<li>
	Phone number:{{i.user.phone_number}}
</li>

<li>
	Language: {{i.get_language_display }}
</li>
<li>
	About agent: {{i.about_me}}
</li>
<li>
	Tour type: {{ i.get_tour_type_display }}
</li>

<li>
	Price :{{i.first_to_ten_price}}
</li>

<li>
	Date of tour : {{i.date_of_tour }}
</li>
<li>
      Quantity : {{i.quantity }}
</li>

<br>
<br>
<br>

{% endfor %}